blank_issues_enabled: false
contact_links:
- name: Questions, feature requests, and more 💬
  url: https://github.com/bytemare/edwards25519/discussions
  about: Do you need help? Did you make something with edwards25519? Do you have an idea? Tell us about it!